# Generated by Django 3.2.2 on 2021-05-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_user', '0002_auto_20210509_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_count',
            field=models.IntegerField(null=True),
        ),
    ]
